### ISSUE TITLE
Migrate from AWS to Digital Ocean

### ISSUE THREAD

**Issue by egillespie** [lansingcodes/api#11]
The cost to host api.lansing.codes, slack.lansing.codes, and lubot on AWS are approximately $15/month. A single droplet on Digital Ocean would lower this cost to $5-10/month.

In addition, hosting is currently paid for by @atomaka. Moving to a Lansing Codes account on Digital Ocean will relieve Andrew of out-of-pocket expenses.

@atomaka What are the monthly usage of memory, hard disk, and CPU for api.lansing.codes, slack.lansing.codes, and lubot on AWS? This will help us pick the appropriate droplet on Digital Ocean.

**Comment by atomaka** [comment]
api.lansing.codes, slack.lansing.codes, and lubot currently run on a t2.micro (https://aws.amazon.com/ec2/instance-types/) from AWS with 30GB of disk.  DigitalOcean's smallest offering should be enough.

**Comment by egillespie** [comment]
Decided to use Netlify functions to push data to Firebase so neither AWS nor Digital Ocean is needed any more. 😁
